export const naturePhotos = [
  { src: '/AnishKalraNature.jpg', alt: 'Anish Kalra laughing on a mountain overlook', position: '50% 28%' },
  { src: '/Cascades1.jpg', alt: 'Anish Kalra hiking in the North Cascades', position: '45% 35%' },
  { src: '/Cascades2.jpg', alt: 'Anish Kalra sitting on a rocky peak in the North Cascades', position: '28% 50%' },
  { src: '/Cascades3.jpg', alt: 'Anish Kalra doing a tree pose on a Cascades trail', position: '50% 32%' },
  { src: '/Cascades4.jpg', alt: 'Anish Kalra on a snowy ridge in the North Cascades', position: '72% 58%' },
  { src: '/Cascades5.jpg', alt: 'Anish Kalra in the North Cascades', position: '50% 72%' },
  { src: '/Cascades6.jpg', alt: 'Anish Kalra by an alpine lake in the North Cascades', position: '22% 52%' },
  { src: '/Cascades7.jpg', alt: 'Anish Kalra above an alpine lake in the North Cascades', position: '78% 78%' },
  { src: '/Rainier1.jpg', alt: 'Anish Kalra at Mount Rainier in a Texas Longhorns shirt', position: '50% 62%' },
  { src: '/Rainier2.jpg', alt: 'Anish Kalra sitting below Mount Rainier', position: '50% 70%' },
  { src: '/Rainier3.jpg', alt: 'Anish Kalra near Mount Rainier', position: '50% 60%' },
  { src: '/Rainier4.jpg', alt: 'Anish Kalra near Mount Rainier', position: '50% 50%' },
  { src: '/Rainier5.jpg', alt: 'Anish Kalra standing below Mount Rainier', position: '50% 74%' },
  { src: '/Rainier6.jpg', alt: 'Anish Kalra in a wildflower meadow near Mount Rainier', position: '50% 76%' },
  { src: '/Si1.jpg', alt: 'Anish Kalra sitting on a fallen log at Mount Si', position: '50% 55%' },
  { src: '/Si2.jpg', alt: 'Anish Kalra hiking at Mount Si', position: '50% 58%' },
  { src: '/Si3.jpg', alt: 'Anish Kalra at Mount Si', position: '58% 60%' },
  { src: '/Si4.jpg', alt: 'Anish Kalra at a Mount Si viewpoint', position: '50% 62%' },
  { src: '/Si5.jpg', alt: 'Anish Kalra at Mount Si', position: '50% 58%' },
  { src: '/Si6.jpg', alt: 'Anish Kalra at Mount Si', position: '50% 50%' },
  { src: '/Snow1.jpg', alt: 'Anish Kalra by a mountain lake', position: '70% 55%' },
  { src: '/Snow2.jpg', alt: 'Anish Kalra sitting by a mountain lake', position: '26% 55%' },
] as const;
